#!/usr/bin/env node

/**
 * Generate environment.prod.ts from environment variables
 * This script replaces placeholders in environment.prod.ts with actual environment variables
 *
 * It is idempotent - safe to run multiple times. The template file must exist with placeholders.
 */

const fs = require('fs');
const path = require('path');

// Template with placeholders - this is what we restore before each replacement
const TEMPLATE = `// Production environment configuration
// This file will be generated by generate-env.js script during build
// to inject environment variables from Amplify or deployment platform

export const environment = {
  production: true,
  apiUrl: '\${API_URL}',
  clientUrl: '\${CLIENT_URL}',
  idpAuthority: '\${IDP_AUTHORITY}',
  azureB2C: {
    clientId: '\${AZURE_B2C_CLIENT_ID}',
    authority: '\${AZURE_B2C_AUTHORITY}',
    knownAuthorities: ['\${AZURE_B2C_KNOWN_AUTHORITY}'],
    redirectUri: '\${AZURE_B2C_REDIRECT_URI}',
    postLogoutRedirectUri: '\${AZURE_B2C_POST_LOGOUT_REDIRECT_URI}',
    scopes: [
      'openid',
      'profile'
    ],
    protectedResourceMap: [] as [string, string[]][]
  }
};
`;

// Define environment variables with fallback defaults
const config = {
  API_URL: process.env.API_URL || 'http://localhost:8010',
  CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:4200',
  IDP_AUTHORITY: process.env.IDP_AUTHORITY || 'https://localhost:9009',
  AZURE_B2C_CLIENT_ID: process.env.AZURE_B2C_CLIENT_ID || 'd0dafab9-cae6-426d-a516-eab88853767c',
  AZURE_B2C_AUTHORITY: process.env.AZURE_B2C_AUTHORITY || 'https://nexttechuit.b2clogin.com/nexttechuit.onmicrosoft.com/B2C_1_SignInSignUp/v2.0/',
  AZURE_B2C_KNOWN_AUTHORITY: process.env.AZURE_B2C_KNOWN_AUTHORITY || 'nexttechuit.b2clogin.com',
  AZURE_B2C_REDIRECT_URI: process.env.AZURE_B2C_REDIRECT_URI || process.env.CLIENT_URL || 'http://localhost:4200',
  AZURE_B2C_POST_LOGOUT_REDIRECT_URI: process.env.AZURE_B2C_POST_LOGOUT_REDIRECT_URI || process.env.CLIENT_URL || 'http://localhost:4200'
};

console.log('\n========================================');
console.log('Generating environment.prod.ts');
console.log('========================================');
console.log('\nEnvironment variables found:');
console.log('- API_URL:', process.env.API_URL ? ('✓ SET to: ' + process.env.API_URL) : '✗ NOT SET (using default: http://localhost:8010)');
console.log('- CLIENT_URL:', process.env.CLIENT_URL ? ('✓ SET to: ' + process.env.CLIENT_URL) : '✗ NOT SET (using default: http://localhost:4200)');
console.log('- IDP_AUTHORITY:', process.env.IDP_AUTHORITY ? '✓ SET' : '✗ NOT SET (using default)');
console.log('- AZURE_B2C_REDIRECT_URI:', process.env.AZURE_B2C_REDIRECT_URI ? '✓ SET' : '✗ NOT SET (using CLIENT_URL)');
console.log('- AZURE_B2C_POST_LOGOUT_REDIRECT_URI:', process.env.AZURE_B2C_POST_LOGOUT_REDIRECT_URI ? '✓ SET' : '✗ NOT SET (using CLIENT_URL)');

console.log('\nFinal configuration:');
console.log(JSON.stringify(config, null, 2));

// Read the template file
const templatePath = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
console.log('\nEnvironment file path:', templatePath);

try {
  // Step 1: Restore template (make script idempotent)
  console.log('\n1. Restoring template file to ensure idempotency...');
  fs.writeFileSync(templatePath, TEMPLATE, 'utf8');
  console.log('   ✓ Template restored');

  // Step 2: Read the template
  console.log('2. Reading template...');
  let template = fs.readFileSync(templatePath, 'utf8');
  console.log('   ✓ Template loaded, length:', template.length, 'bytes');

  // Step 3: Replace placeholders with actual values
  console.log('3. Replacing placeholders with environment values...');
  let replacementCount = 0;
  Object.keys(config).forEach(key => {
    const placeholder = `\${${key}}`;
    const value = config[key];
    const beforeLength = template.length;
    template = template.split(placeholder).join(value);
    const afterLength = template.length;
    if (beforeLength !== afterLength) {
      replacementCount++;
      console.log(`   ✓ ${placeholder} → ${value}`);
    } else {
      console.log(`   ✗ Placeholder not found: ${placeholder}`);
    }
  });
  console.log('   Total replacements made:', replacementCount);

  // Step 4: Write the generated file
  console.log('4. Writing generated file...');
  fs.writeFileSync(templatePath, template, 'utf8');
  console.log('   ✓ File written successfully');

  // Step 5: Verify the file
  console.log('5. Verifying file contains correct values...');
  const verification = fs.readFileSync(templatePath, 'utf8');
  const apiUrlMatch = verification.match(/apiUrl:\s*'([^']+)'/);
  if (apiUrlMatch) {
    console.log('   ✓ apiUrl in file:', apiUrlMatch[1]);
    if (apiUrlMatch[1].includes('$')) {
      console.error('   ✗ ERROR: apiUrl still contains placeholder!', apiUrlMatch[1]);
      process.exit(1);
    }
  } else {
    console.error('   ✗ ERROR: Could not find apiUrl in generated file!');
    process.exit(1);
  }

  console.log('\n========================================');
  console.log('✓ SUCCESS! Environment file generated\n');

} catch (error) {
  console.error('\n========================================');
  console.error('✗ ERROR:', error.message);
  console.error('========================================\n');
  process.exit(1);
}
