apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-basketdb
  namespace: default
  labels:
    app.kubernetes.io/name: basketdb
    app.kubernetes.io/instance: eshopping-basketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: basketdb
      app.kubernetes.io/instance: eshopping-basketdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: basketdb
        app.kubernetes.io/instance: eshopping-basketdb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: basketdb
          image: redis:alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-basketdb
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: basketdb
    app.kubernetes.io/instance: eshopping-basketdb
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
