/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdEditRouteImport } from './routes/products.$id.edit'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as BrandsTypesRouteImport } from './routes/brands-types'
import { Route as ActivitiesRouteImport } from './routes/activities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsTypesRoute = BrandsTypesRouteImport.update({
  id: '/brands-types',
  path: '/brands-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/orders': typeof OrdersRoute
  '/brands-types': typeof BrandsTypesRoute
  '/activities': typeof ActivitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/orders': typeof OrdersRoute
  '/brands-types': typeof BrandsTypesRoute
  '/activities': typeof ActivitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/orders': typeof OrdersRoute
  '/brands-types': typeof BrandsTypesRoute
  '/activities': typeof ActivitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products' | '/products/new' | '/products/$id/edit' | '/orders' | '/brands-types' | '/activities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/products/new' | '/products/$id/edit' | '/orders' | '/brands-types' | '/activities'
  id: '__root__' | '/' | '/products' | '/products/new' | '/products/$id/edit' | '/orders' | '/brands-types' | '/activities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsIdEditRoute: typeof ProductsIdEditRoute
  OrdersRoute: typeof OrdersRoute
  BrandsTypesRoute: typeof BrandsTypesRoute
  ActivitiesRoute: typeof ActivitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id/edit': {
      id: '/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands-types': {
      id: '/brands-types'
      path: '/brands-types'
      fullPath: '/brands-types'
      preLoaderRoute: typeof BrandsTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
  OrdersRoute: OrdersRoute,
  BrandsTypesRoute: BrandsTypesRoute,
  ActivitiesRoute: ActivitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
