{{- $name := include "ocelotapigw.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "ocelotapigw.name" . }}
    chart: {{ template "ocelotapigw.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ElasticConfiguration__Uri: http://eshopping-elasticsearch:9200
  ocelot.k8s.json: |
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/v1/Catalog",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT" ],
          "FileCacheOptions": { "TtlSeconds": 30 }
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetProductById/{id}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetProductById/{id}",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/CreateProduct",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/CreateProduct",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllProducts",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllProducts",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllBrands",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllBrands",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllTypes",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllTypes",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/GetBasket/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-basket",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Basket/GetBasket/{userName}",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/DeleteBasket/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-basket",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Basket/DeleteBasket/{userName}",
          "UpstreamHttpMethod": [ "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/CreateBasket",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-basket",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Basket/CreateBasket",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/Checkout",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-basket",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/api/v1/Basket/Checkout",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v2/Basket/Checkout",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-basket",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/api/v2/Basket/Checkout",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Discount/{productName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-discount",
              "Port": "8080"
            }
          ],
          "UpstreamPathTemplate": "/Discount/{productName}",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Order/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-ordering",
              "Port": "8080"
            }
          ],
          "UpstreamPathTemplate": "/Order/{userName}",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Order",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-ordering",
              "Port": "8080"
            }
          ],
          "UpstreamPathTemplate": "/Order",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/UploadProductImage",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/UploadProductImage",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Admin/MigrateImagesToS3",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "eshopping-catalog",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Admin/MigrateImagesToS3",
          "UpstreamHttpMethod": [ "POST" ]
        }
      ],
      "GlobalConfiguration": {
        "BaseUrl": "http://ocelotapigw"
      }
    }