apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-ordering
  namespace: default
  labels:
    app.kubernetes.io/name: ordering
    app.kubernetes.io/instance: eshopping-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ordering
      app.kubernetes.io/instance: eshopping-ordering
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ordering
        app.kubernetes.io/instance: eshopping-ordering
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: ordering
          image: orderingapi:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-ordering
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ordering
    app.kubernetes.io/instance: eshopping-ordering
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
