apiVersion: v1
kind: ConfigMap
metadata:
  name: test-k6-provider
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'Test K6'
      orgId: 1
      folder: 'Test'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/test-k6