apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-discount
  namespace: default
  labels:
    app.kubernetes.io/name: discount
    app.kubernetes.io/instance: eshopping-discount
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discount
      app.kubernetes.io/instance: eshopping-discount
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discount
        app.kubernetes.io/instance: eshopping-discount
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: discount
          image: discountapi:latest
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-discount-discount-grpc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discount
    app.kubernetes.io/instance: eshopping-discount
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
