apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana.fullname" . }}-config
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
data:
  kibana.yml: |
{{ .Values.kibanaConfig.config | indent 4 }}