apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: ecommerce
data:
  MONGODB_URL: "mongodb://mongo-service:27017"
  MONGO_DB: "CatalogDb"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  ASPNETCORE_ENVIRONMENT: "Development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-config
  namespace: ecommerce
data:
  CacheSettings__ConnectionString: "redis-service:6379"
  GrpcSettings__DiscountUrl: "http://discount-service:80"
  EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq-service:5672"
  ASPNETCORE_ENVIRONMENT: "Development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discount-config
  namespace: ecommerce
data:
  DatabaseSettings__ConnectionString: "Server=postgres-service;Port=5432;Database=DiscountDb;User Id=admin;Password=password123;"
  ASPNETCORE_ENVIRONMENT: "Development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-config
  namespace: ecommerce
data:
  ConnectionStrings__OrderingConnectionString: "Server=sqlserver-service;Database=OrderDb;User Id=sa;Password=Password123;TrustServerCertificate=true"
  EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq-service:5672"
  ASPNETCORE_ENVIRONMENT: "Development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  GlobalConfiguration__BaseUrl: "http://ocelotapigw-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: ecommerce
data:
  discovery.type: "single-node"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  xpack.security.enabled: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: ecommerce
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-service:9200"
  SERVER_NAME: "kibana"
  SERVER_HOST: "0.0.0.0"
