apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-api-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: catalog-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: basket-api-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: basket-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: discount-api-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: discount-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ordering-api-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ordering-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ocelot-gateway-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ocelot-gateway
