apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-discountdb
  namespace: default
  labels:
    app.kubernetes.io/name: discountdb
    app.kubernetes.io/instance: eshopping-discountdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discountdb
      app.kubernetes.io/instance: eshopping-discountdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discountdb
        app.kubernetes.io/instance: eshopping-discountdb
    spec:
      containers:
        - name: discountdb
          image: postgres:13-alpine
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin1234"
            - name: POSTGRES_DB
              value: "DiscountDb"
          resources: {}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-discountdb
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discountdb
    app.kubernetes.io/instance: eshopping-discountdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
