apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-configmap
data:
  ElasticConfiguration__Uri: "http://elasticsearch-service:9200"
  ocelot.k8s.json: |
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/v1/Catalog",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog-api-service",
              "Port": "9000"
            }
          ],
          "UpstreamPathTemplate": "/Catalog",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT" ],
          "FileCacheOptions": { "TtlSeconds": 30 }
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetProductById/{id}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog-api-service",
              "Port": "9000"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetProductById/{id}",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllProducts",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog-api-service",
              "Port": "9000"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllProducts",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllBrands",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog-api-service",
              "Port": "9000"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllBrands",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Catalog/GetAllTypes",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog-api-service",
              "Port": "9000"
            }
          ],
          "UpstreamPathTemplate": "/Catalog/GetAllTypes",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/GetBasket/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket-api-service",
              "Port": "9001"
            }
          ],
          "UpstreamPathTemplate": "/Basket/GetBasket/{userName}",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/DeleteBasket/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket-api-service",
              "Port": "9001"
            }
          ],
          "UpstreamPathTemplate": "/Basket/DeleteBasket/{userName}",
          "UpstreamHttpMethod": [ "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/CreateBasket",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket-api-service",
              "Port": "9001"
            }
          ],
          "UpstreamPathTemplate": "/Basket/CreateBasket",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Basket/Checkout",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket-api-service",
              "Port": "9001"
            }
          ],
          "UpstreamPathTemplate": "/api/v1/Basket/Checkout",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v2/Basket/Checkout",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket-api-service",
              "Port": "9001"
            }
          ],
          "UpstreamPathTemplate": "/api/v2/Basket/Checkout",
          "UpstreamHttpMethod": [ "POST" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Discount/{productName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "discount-api-service",
              "Port": "80"
            }
          ],
          "UpstreamPathTemplate": "/Discount/{productName}",
          "UpstreamHttpMethod": [ "GET", "DELETE" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Order/{userName}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "ordering-api-service",
              "Port": "9003"
            }
          ],
          "UpstreamPathTemplate": "/Order/{userName}",
          "UpstreamHttpMethod": [ "GET" ]
        },
        {
          "DownstreamPathTemplate": "/api/v1/Order",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "ordering-api-service",
              "Port": "9003"
            }
          ],
          "UpstreamPathTemplate": "/Order",
          "UpstreamHttpMethod": [ "POST" ]
        }
      ],
      "GlobalConfiguration": {
        "BaseUrl": "http://ocelot-apigw-service"
      }
    }
