// Production environment configuration
// This file will be generated by generate-env.js script during build
// to inject environment variables from Amplify or deployment platform

export const environment = {
  production: true,
  apiUrl: '${API_URL}',
  clientUrl: '${CLIENT_URL}',
  idpAuthority: '${IDP_AUTHORITY}',
  azureB2C: {
    clientId: '${AZURE_B2C_CLIENT_ID}',
    authority: '${AZURE_B2C_AUTHORITY}',
    knownAuthorities: ['${AZURE_B2C_KNOWN_AUTHORITY}'],
    redirectUri: '${AZURE_B2C_REDIRECT_URI}',
    postLogoutRedirectUri: '${AZURE_B2C_POST_LOGOUT_REDIRECT_URI}',
    scopes: [
      'openid',
      'profile'
    ],
    protectedResourceMap: [] as [string, string[]][]
  }
};
