apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-basket
  namespace: default
  labels:
    app.kubernetes.io/name: basket
    app.kubernetes.io/instance: eshopping-basket
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: basket
      app.kubernetes.io/instance: eshopping-basket
  template:
    metadata:
      labels:
        app.kubernetes.io/name: basket
        app.kubernetes.io/instance: eshopping-basket
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: basket
          image: eshop/basket.api:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-basket
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: basket
    app.kubernetes.io/instance: eshopping-basket
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
