apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopping-orderdb
  namespace: default
  labels:
    app.kubernetes.io/name: orderdb
    app.kubernetes.io/instance: eshopping-orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orderdb
      app.kubernetes.io/instance: eshopping-orderdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orderdb
        app.kubernetes.io/instance: eshopping-orderdb
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: orderdb
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - name: sqlserver
              containerPort: 1433
              protocol: TCP
          env:
            - name: SA_PASSWORD
              value: "SqlPassword123"
            - name: ACCEPT_EULA
              value: "Y"
          resources: {}
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
      volumes:
        - name: sqlserver-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eshopping-orderdb
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orderdb
    app.kubernetes.io/instance: eshopping-orderdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
