apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-configmap
data:
  sqlserver-url: "Server=sqlserver-service,1433;Database=OrderDb;User Id=sa;Password=SwN12345678!;TrustServerCertificate=True"
