replicaCount: 1

image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "pgadmin"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "standard"  # Changed from gp2 to standard for Minikube compatibility
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  pgadminEmail: "admin@example.com"
  pgadminPassword: "admin1234"
