replicaCount: 1

image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 5050

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  storageClass: "gp2"  # AWS EKS storage class
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  pgadminEmail: "admin@example.com"
  pgadminPassword: "admin1234"
