apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discount-grpc.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  DatabaseSettings__ConnectionString: Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;Pooling=true;SSL Mode=Disable;
  ElasticConfiguration__Uri: http://elasticsearch:9200